In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn import linear_model, neighbors, ensemble, naive_bayes, svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, confusion_matrix, classification_report
from sklearn import preprocessing

import plotly
plotly.tools.set_credentials_file(username='extralime', api_key='q3tUGZrv40fkKyR4uPuL')
import plotly.plotly as py

from IPython.display import Image

import warnings

warnings.filterwarnings(
    module='scipy',
    action='ignore',
    message='Using a')

/root/.pyenv/versions/3.6.0/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/root/.pyenv/versions/3.6.0/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [2]:
df = pd.read_csv('lemon_train.csv')

In [3]:
df.drop(['RefId', 'BYRNO', 'AUCGUART', 'PRIMEUNIT','PurchDate',
         'VNZIP1','WheelType', 'VehYear'],1,inplace=True)

In [4]:
df.dropna(inplace=True)

In [7]:
models = df.Model
submods = df.SubModel
trims = df.Trim
chars = df[['Model','SubModel','Trim']]

In [8]:
md = chars.SubModel[0:1000]
keywords = ['4D', '2D', 'SEDAN', 'V6', 'V8', '4C', 'FWD','RWD','2WD','4WD','AWD',
            'CAB','MINIVAN','SUV','UTILITY','PICKUP','COUPE','SUV','SPORT','PASSENGER',
           'WAGON','LIMITED']

In [ ]:
val_sets = pd.DataFrame()
for key in keyword:
    for i in md.SubModel:
        beg = 
        vals = np.where(df.SubModel.str.contains('' + str(key) + ''),1,0)
    val_sets[key] = vals

In [40]:
en_sizes = chars.SubModel[0:1000].str.split('.').reset_index()

## Find the most common engine sizes in the SubModel category

In [ ]:
#The model and submodel field are messy qith quite a bit of additional information.
#We want to extract the most common engine size

In [91]:
df.head()

,IsBadBuy,Auction,VehicleAge,Make,Model,Trim,SubModel,Color,Transmission,WheelTypeID,...,MMRAcquisitionRetailAveragePrice,MMRAcquisitonRetailCleanPrice,MMRCurrentAuctionAveragePrice,MMRCurrentAuctionCleanPrice,MMRCurrentRetailAveragePrice,MMRCurrentRetailCleanPrice,VNST,VehBCost,IsOnlineSale,WarrantyCost
0,0,ADESA,3,MAZDA,MAZDA3,i,4D SEDAN I,RED,AUTO,1.0,...,11636.0,13600.0,7451.0,8552.0,11597.0,12409.0,FL,7100.0,0,1113
1,0,ADESA,5,DODGE,1500 RAM PICKUP 2WD,ST,QUAD CAB 4.7L SLT,WHITE,AUTO,1.0,...,10897.0,12572.0,7456.0,9222.0,11374.0,12791.0,FL,7600.0,0,1053
2,0,ADESA,4,DODGE,STRATUS V6,SXT,4D SEDAN SXT FFV,MAROON,AUTO,2.0,...,6943.0,8457.0,4035.0,5557.0,7146.0,8702.0,FL,4900.0,0,1389
3,0,ADESA,5,DODGE,NEON,SXT,4D SEDAN,SILVER,AUTO,1.0,...,4658.0,5690.0,1844.0,2646.0,4375.0,5518.0,FL,4100.0,0,630
4,0,ADESA,4,FORD,FOCUS,ZX3,2D COUPE ZX3,SILVER,MANUAL,2.0,...,7723.0,8707.0,3247.0,4384.0,6739.0,7911.0,FL,4000.0,0,1020

In [87]:
test = list(chars.SubModel)

In [90]:
test

['4D SEDAN I',
 'QUAD CAB 4.7L SLT',
 '4D SEDAN SXT FFV',
 '4D SEDAN',
 '2D COUPE ZX3',
 '4D SEDAN ES',
 '4D SEDAN EX',
 '4D SEDAN SE',
 '4D SEDAN EX',
 '4D SEDAN SEL',
 'REG CAB 4.3L',
 'REG CAB 4.2L XL',
 'MINIVAN 3.3L',
 '4D SEDAN',
 'MINIVAN 3.8L',
 '2D COUPE',
 '4D SUV 4.2L',
 '4D SEDAN',
 '4D UTILITY 4.2L SLE',
 'MINIVAN 3.3L',
 '2D COUPE SS',
 'PASSENGER 3.4L',
 '4D SUV 2.2L LS',
 '4D SUV 2.2L LS',
 '4D SEDAN LS PREMIUM',
 '4D UTILITY 4.2L SLE',
 'QUAD CAB 4.7L SLT',
 '4D SUV 5.7L SLT',
 'MINIVAN 3.8L SXT',
 '4D UTILITY 5.3L FFV LS',
 '2D SUV 4.0L SPORT',
 '4D SEDAN',
 '2D COUPE',
 '4D SUV-PICKUP 5.3L',
 'PASSENGER 3.8L LX',
 'PASSENGER 3.9L LX',
 '4D SEDAN',
 '4D SEDAN',
 '4D WAGON SXT',
 '4D SEDAN LS 3.5L FFV',
 'QUAD CAB 5.7L',
 '4D SEDAN SE',
 '4D SEDAN SE',
 'QUAD CAB 4.7L',
 '4D SEDAN LEVEL 2',
 '4D SUV 2.2L LS',
 '4D SEDAN',
 '2D COUPE ZX3',
 '4D SUV 4.7L',
 '4D SEDAN SEL',
 '4D SUV 4.7L ADVENTURER',
 '4D SEDAN GLS',
 '4D SEDAN',
 '2D COUPE',
 '4D SEDAN SE',
 '4D SPORT UTILITY SPORT EDITION',
 'MINIVAN 3.8L SXT',
 '4D SEDAN',
 '4D SEDAN GXP',
 '4D SEDAN',
 '2D COUPE ZX3',
 '4D SUV',
 '4D SEDAN LEVEL 2',
 '4D SEDAN SE',
 'QUAD CAB 3.7L ST',
 '4D SUV 5.3L',
 '4D SEDAN LS',
 '4D SUV',
 '4D SUV 4.7L ST',
 '4D SPORT UTILITY EX',
 '4D SUV 2.2L LT',
 '4D SUV 4.6L XLT',
 '2D COUPE',
 '4D SEDAN SES',
 '4D CUV 3.0L SEL',
 'CREW CAB 5.4L KING RANCH',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SUV 4.2L LS',
 '4D SUV 4.2L LS',
 '4D SEDAN',
 '4D SEDAN',
 '4D SUV HARDTOP 2.5L LT',
 'QUAD CAB 5.7L',
 '2D COUPE',
 'QUAD CAB 4.7L SLT',
 'PASSENGER 3.9L LX',
 '4D SEDAN',
 'QUAD CAB 5.7L SLT',
 '4D SEDAN',
 '4D SUV 3.7L',
 '4D SUV 4.6L XLS',
 '4D SEDAN',
 'QUAD CAB 4.7L FFV BIG HORN',
 '4D SUV 4.2L',
 '4D SEDAN LS',
 '4D SEDAN GL1',
 '2D COUPE',
 'MINIVAN 3.3L LX',
 '4D SEDAN LE',
 '4D SUV 4.7L ADVENTURER',
 '4D SEDAN',
 'WAGON 2.7L',
 '4D SUV LS',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SUV 2.2L LT',
 '4D SUV SPORT',
 '4D SEDAN',
 '4D SEDAN LS',
 'MINIVAN 3.8L',
 '4D SEDAN LEVEL 1',
 '4D SEDAN I',
 '4D SEDAN',
 '4D SEDAN LE',
 '4D CUV 3.0L SE',
 '4D SEDAN SE',
 '4D SEDAN ES',
 '4D SUV LIMITED',
 '4D SEDAN SE',
 '4D WAGON',
 '5D SEDAN GS',
 '4D SEDAN',
 '4D SUV 4.6L EDDIE BAUER',
 '4D SUV 5.4L EDDIE BAUER',
 'REG CAB 3.7L',
 '4D SEDAN EX',
 '4D SEDAN',
 '4D MINIVAN EXT 3.4L GLS',
 '4D CUV 3.0L XLT',
 '4D SEDAN',
 '4D SEDAN',
 '2D COUPE',
 '4D SEDAN LEVEL 3',
 '4D SEDAN',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SEDAN',
 '2D EXT CAB 3.0L EDGE',
 '4D WAGON ZTW',
 '4D SEDAN SE',
 'QUAD CAB 4.7L SLT',
 '2D COUPE LS',
 '4D SUV 4.7L SLT',
 '4D CUV 3.0L XLT',
 '4D SEDAN SE',
 '4D SEDAN LS',
 '4D UTILITY 4.2L SLE',
 '4D SEDAN L200',
 '4D SEDAN GLS',
 'PASSENGER EXT 3.5L',
 '4D SEDAN SE',
 '4D SEDAN',
 '2D COUPE',
 '4D SEDAN',
 '4D SEDAN LS',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SEDAN LEVEL 3',
 '4D SEDAN',
 'EXT CAB 4.8L',
 '4D SUV 4.0L FFV XLT',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SPORT UTILITY LS',
 '4D SEDAN',
 '4D SEDAN SEL FFV',
 '4D SEDAN SEL',
 '4D SEDAN',
 '4D SEDAN SE FFV',
 'WAGON 3.5L',
 '4D SPORT TOURING',
 '4D SEDAN LS',
 '4D SEDAN',
 '4D WAGON',
 '4D SEDAN ZX4 SE',
 '4D SEDAN GL',
 '4D SEDAN LT 3.5L',
 '4D WAGON',
 '4D SUV 4.6L XLT',
 '4D SEDAN LS',
 '4D SUV-PICKUP 5.3L',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D CUV',
 '5D SEDAN GS',
 '4D SEDAN S',
 'EXT CAB 3.7L',
 'PASSENGER EXT 3.5L LS',
 '4D WAGON',
 '4D SEDAN',
 '4D SEDAN LS',
 '4D SEDAN CE',
 '4D SPORT UTILITY I',
 '4D SEDAN GLS',
 '4D SEDAN I',
 '4D WAGON',
 '4D SEDAN',
 '4D SEDAN GLS',
 '4D SUV 2.2L LS',
 '4D SUV CX',
 '4D SEDAN LT 3.5L FFV',
 '4D SEDAN LEVEL 1',
 '4D SEDAN EX',
 '4D SEDAN',
 '4D SEDAN',
 'REG CAB 4.2L STX',
 '4D SEDAN LT 3.5L',
 '4D SPORT TOURING',
 '4D SEDAN SE1',
 '4D SEDAN SEL',
 '4D WAGON SE',
 '4D SUV LS',
 '4D SEDAN LX AUTO',
 '4D CUV 2.3L XLS',
 '4D SEDAN',
 '4D SEDAN',
 '2D COUPE SE',
 '4D SEDAN LS',
 '4D SUV 2.2L LT',
 '4D SEDAN ZX4',
 'REG CAB 2.8L',
 '4D SEDAN LS',
 '2D COUPE',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SUV LS',
 '4D SUV 4.2L LS',
 '4D SEDAN',
 '4D SEDAN LEVEL 2',
 '4D UTILITY 4.2L SLE',
 '4D SEDAN SE',
 '4D CUV 2.7L',
 '4D WAGON LAREDO',
 '4D SEDAN SE COMFORT',
 '4D SEDAN GL',
 '4D SEDAN LS',
 '4D SEDAN LT 3.5L',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN SXT FFV',
 '4D SPORT UTILITY LS',
 '4D SEDAN',
 '4D SEDAN LS',
 '4D SEDAN LEVEL 2',
 '4D SEDAN LX',
 'MINIVAN 3.3L SPORT',
 'REG CAB 4.3L',
 '4D SEDAN 2.7L SE',
 '4D SEDAN',
 '4D SEDAN CE',
 '4D SEDAN SXT FFV',
 '4D SPORT',
 '4D SEDAN',
 '4D SUV LS',
 '4D SEDAN',
 '4D SEDAN GS',
 '4D SUV HARDTOP 2.5L',
 '4D SUV 2.2L LS',
 '2D COUPE',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN LT',
 '4D SPORT UTILITY I',
 '4D SUV 3.7L',
 '4D SUV',
 '4D SEDAN I',
 '4D SEDAN',
 '4D SEDAN LS PREMIUM',
 'EXT CAB 4.8L',
 '4D SPORT UTILITY EX',
 '4D SPORT UTILITY SE',
 '4D SEDAN XE',
 '4D SUV 4.6L XLS',
 '4D SUV 2.2L LS',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN ES',
 '4D SEDAN',
 '4D SEDAN EX',
 'MINIVAN 3.8L SXT',
 '4D SEDAN LS',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 'REG CAB 4.6L STX',
 '4D SEDAN LT 3.5L',
 '4D SUV 5.7L SLT',
 '4D SPORT UTILITY S',
 '4D WAGON SXT',
 '4D SEDAN GL',
 'EXT CAB 4.6L STX',
 '4D SEDAN LT 3.5L',
 '4D SEDAN SE',
 '4D SEDAN SE',
 '4D SUV',
 '4D SPORT UTILITY SE',
 '4D SEDAN LT 3.5L',
 '4D WAGON CX',
 '2D COUPE ZX3',
 '4D SEDAN S',
 '4D SEDAN S',
 '4D SUV LS',
 '4D SUV RENEGADE',
 '4D SPORT UTILITY LS',
 '4D WAGON',
 '4D SEDAN LS',
 '4D SEDAN',
 '4D SEDAN SE',
 '4D SEDAN SE FFV',
 'MINIVAN 3.3L SE',
 '4D SEDAN',
 '4D SEDAN',
 'MINIVAN 3.3L',
 '4D SEDAN TOURING TURBO',
 '2D CONVERTIBLE LX',
 '4D SEDAN LTZ',
 '4D SEDAN LS',
 'PASSENGER 3.8L LX',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 'PASSENGER 3.5L LS',
 '4D SEDAN',
 '4D SEDAN LS',
 '4D SEDAN SXT',
 '4D SEDAN',
 '4D CUV 2.7L GLS',
 '4D SEDAN GLS',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SEDAN',
 'REG CAB 4.3L',
 '4D SEDAN LX',
 '4D SEDAN ZTS',
 '4D HATCHBACK S',
 '4D SEDAN LS',
 '4D WAGON',
 '4D SUV 4.0L FFV XLS',
 '4D SEDAN',
 '4D SEDAN SE',
 '4D SEDAN 1.8',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN SEL',
 '4D SEDAN SXT',
 'MINIVAN 3.8L SPORT',
 '4D SEDAN',
 '4D SEDAN SE',
 '4D SUV 3.7L SLT',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SEDAN',
 'PASSENGER 3.9L LX',
 'EXT CAB 4.6L FX2 SPORT',
 '4D SEDAN PKG1',
 '2D CONVERTIBLE GTC',
 '4D SEDAN',
 '4D SEDAN CE',
 '4D SEDAN SXT FFV',
 'QUAD CAB 4.7L SLT',
 '4D SEDAN LT 3.9L',
 '4D SEDAN LS',
 '4D UTILITY 4.2L SLE',
 '4D PASSENGER 3.8L SE',
 '4D SEDAN EX',
 '4D WAGON',
 '4D SEDAN LS SPORT',
 '4D SUV CX',
 '4D SEDAN LEVEL 3',
 '4D SUV 4.7L ADVENTURER',
 '4D SUV 4.2L LS',
 '4D SEDAN',
 'EXT CAB 4.6L FX2 SPORT',
 '4D SEDAN',
 '4D SEDAN SE FFV',
 '4D SEDAN LS',
 '4D SPORT',
 '4D SEDAN LS',
 '4D SEDAN',
 '4D SPORT UTILITY EX',
 'PASSENGER EXT 3.5L',
 'PASSENGER EXT 3.4L LS',
 '4D SUV HARDTOP 2.5L',
 '4D SEDAN LS',
 '2D COUPE',
 '4D SUV',
 '4D SEDAN',
 '4D SUV 5.4L XLT',
 '4D SEDAN 2.7L',
 '4D SEDAN LX',
 '2D COUPE LS',
 'WAGON 2.7L',
 '4D SEDAN',
 '4D SEDAN LEVEL 2',
 '4D SEDAN',
 'WAGON 2.7L',
 '4D SEDAN',
 '4D SEDAN CLASSIC',
 '4D SEDAN SEL',
 '4D SEDAN LT',
 '4D SEDAN',
 '4D SEDAN LEVEL 2',
 '4D SEDAN',
 '4D SUV 3.0L',
 '2D CONVERTIBLE TOURING',
 '4D SEDAN',
 '4D SEDAN LS',
 '4D SEDAN TOURING',
 '4D SEDAN',
 '2D COUPE',
 '4D SUV 4.2L LS',
 'SPORT UTILITY',
 '4D SEDAN',
 '4D SUV',
 '4D SUV 2.2L LT',
 'WAGON 2.7L',
 '4D SUV 4.2L LS',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN LS',
 '2D SPYDER GT',
 '4D SEDAN',
 '4D SEDAN SE1',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SEDAN LXI',
 '4D SEDAN LT',
 '4D SEDAN LEVEL 2',
 '4D SEDAN LEVEL 2',
 '4D SEDAN SE-R',
 '4D SEDAN LS PREMIUM',
 '2D CONVERTIBLE TOURING',
 'MINIVAN 3.8L LXI',
 'EXT CAB 5.3L LS',
 '4D SEDAN GT2',
 '4D SPORT UTILITY LX',
 '4D SEDAN CLASSIC',
 '4D SEDAN LS',
 '4D SUV 5.7L SLT',
 '4D SEDAN LS',
 '4D SEDAN',
 '2D COUPE LT',
 '4D SEDAN',
 '4D SPORT',
 '4D SEDAN',
 '4D WAGON',
 '4D SEDAN I',
 '4D SUV 4.2L LS',
 '4D SEDAN LS',
 'PASSENGER EXT 3.5L',
 '2D COUPE EX AUTO',
 'MINIVAN 3.8L',
 '4D SEDAN',
 '4D CUV 3.0L XLS',
 '4D SPORT TOURING',
 '4D SUV CX',
 '4D SEDAN LT 3.5L',
 '4D SEDAN LX',
 '4D SEDAN',
 '4D CUV 3.0L SEL',
 '4D SEDAN S',
 '4D SEDAN',
 '4D SEDAN PREMIER',
 '4D WAGON',
 '2D COUPE LS',
 '4D SEDAN I',
 '4D WAGON LAREDO',
 '4D SEDAN',
 '4D SEDAN SE',
 '4D SEDAN LT',
 '4D SEDAN',
 '4D SEDAN LE',
 '4D SEDAN',
 '4D SEDAN ZX4',
 '4D SEDAN',
 '4D SEDAN LS',
 '4D SUV 4.0L XLT',
 '4D SEDAN EX AUTO',
 '4D SEDAN',
 '4D SEDAN',
 '2D COUPE',
 '4D SEDAN LEVEL 2',
 '4D SEDAN S',
 '4D SEDAN CLASSIC',
 '4D SUV SPORT',
 '2D COUPE',
 '4D SEDAN GT',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN LT 3.5L',
 '4D SEDAN LT 3.5L',
 '4D SEDAN LEVEL 2',
 '4D SEDAN',
 '4D SEDAN SE1',
 '4D SUV 5.7L LIMITED',
 '4D SEDAN',
 '4D SEDAN 2.7L',
 'MINIVAN 2.4L',
 '4D SPORT UTILITY',
 '4D SEDAN EX AUTO',
 '4D CUV 3.0L SE',
 '4D SEDAN SES',
 '4D SEDAN LX AUTO',
 '4D SEDAN',
 '4D SPORT',
 '4D SEDAN LIMITED',
 '4D SEDAN',
 '4D SEDAN LX',
 'CREW CAB 5.3L',
 '4D SEDAN LXI',
 '4D SEDAN SE',
 '2D COUPE',
 '2D COUPE',
 '4D SEDAN GT2',
 '4D SEDAN S',
 'MINIVAN 3.8L',
 '4D SEDAN SE1',
 '4D SUV RENEGADE',
 '4D SEDAN SL2',
 'PASSENGER 3.9L LX',
 '4D SEDAN',
 '4D SEDAN LX',
 '4D SEDAN LS',
 '4D SEDAN LT',
 '4D SEDAN',
 '4D SEDAN SEL',
 '4D SUV 4.7L',
 '4D SUV 4.0L FFV XLT',
 '4D PASSENGER 3.8L SEL',
 '4D SEDAN GS',
 '4D SUV LS',
 '4D SPORT UTILITY',
 '4D SEDAN',
 '4D SUV 4.2L LS',
 '4D SEDAN',
 '4D SEDAN GLS',
 '4D SEDAN ES',
 '4D SEDAN',
 '4D SPORT',
 '4D SEDAN LT 3.9L',
 '4D WAGON SXT',
 '4D SEDAN GXE',
 '4D SEDAN LT 3.5L',
 '4D SEDAN LT 3.5L',
 '4D SUV 5.7L SLT',
 '2D COUPE',
 '4D SUV 5.4L XLT',
 '4D SEDAN SE',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SPORT UTILITY',
 '2D COUPE',
 '4D HATCHBACK S',
 '2D COUPE EX AUTO',
 '4D SEDAN SE AUTO',
 '2D COUPE',
 '4D SEDAN LT',
 '4D SEDAN',
 '4D SEDAN ES HIGHLINE',
 '4D SEDAN SE1',
 '4D SUV 5.9L SLT',
 '4D SEDAN',
 '4D SUV 4.2L',
 '4D SUV 4.7L',
 '4D SEDAN LS',
 'EXT CAB 5.3L',
 '4D SEDAN',
 '4D SEDAN',
 '4D SPORT TOURING',
 '4D SPORT UTILITY EX',
 '4D SEDAN',
 'PASSENGER 3.9L',
 '4D UTILITY 4.2L SLE',
 '4D SUV CX',
 '4D CUV 3.0L XLT',
 '4D SEDAN SL1',
 '4D SUV 2.2L LS',
 '4D SEDAN CE',
 '4D SEDAN CUSTOM',
 '4D SUV 4.0L XLT',
 '4D SEDAN I',
 '4D SPORT TOURING',
 '4D SEDAN LS',
 'QUAD CAB 3.7L',
 '4D SUV 4.2L LS',
 '4D SEDAN SEL',
 'REG CAB 4.3L',
 '4D SEDAN 1.8',
 '4D SEDAN ES',
 '2D COUPE',
 '4D SPORT UTILITY ES',
 '4D SUV 4.2L LS',
 'MINIVAN 3.3L',
 '4D SEDAN LUXURY',
 'REG CAB 2.2L FFV',
 '2D COUPE EX AUTO',
 '4D SEDAN SE',
 '2D COUPE',
 '4D SEDAN SEL',
 '4D SEDAN',
 'MINIVAN 3.3L',
 '4D SEDAN SES DURATEC',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN GLS',
 '4D SUV 4.7L ADVENTURER',
 '4D SEDAN',
 '4D SEDAN GXE',
 '4D SEDAN',
 '4D SEDAN LS',
 '2D COUPE GS',
 'REG CAB 4.2L STX',
 '4D SEDAN 1.8',
 '4D SEDAN',
 '4D SUV SPORT',
 '4D SEDAN SE',
 '4D SEDAN S',
 '4D SUV 4.0L FFV XLT',
 '2D COUPE',
 'CREW CAB 4.6L XLT',
 '4D SUV LS',
 '4D SEDAN LS',
 '4D SUV 4.7L',
 '4D SEDAN LS',
 '4D WAGON',
 '4D SEDAN',
 '4D SEDAN',
 'QUAD CAB 4.7L SLT',
 '4D SEDAN PREMIER',
 '4D SUV-PICKUP 5.3L',
 '4D SEDAN PREMIER',
 '4D SEDAN ZTS',
 '4D SEDAN',
 '4D SEDAN LX',
 '4D SEDAN DE',
 '4D SEDAN',
 '4D CUV 3.0L XLT',
 '4D SEDAN GLS',
 '4D SEDAN',
 '4D SEDAN SE1',
 '4D SEDAN LS',
 '4D SUV LT',
 '4D UTILITY 4.2L SLE',
 '4D SEDAN GLS',
 '4D SUV 4.0L FFV XLS',
 '4D SEDAN TOURING',
 '4D SEDAN SE',
 '4D SEDAN 2.7L',
 '4D WAGON',
 '4D SEDAN LIMITED',
 '4D SEDAN I',
 '4D SEDAN S',
 '4D SEDAN LS',
 '4D SEDAN GL2',
 '4D SUV 4.2L LS',
 '4D SEDAN',
 '4D SEDAN LS',
 '4D SUV 5.3L FFV LS',
 '4D SEDAN LT 3.9L',
 '4D SEDAN TOURING',
 '4D SEDAN LEVEL 3',
 '4D SEDAN I',
 '4D SEDAN',
 '4D SEDAN 1.8',
 'MINIVAN 3.8L SXT',
 '4D SPORT UTILITY S',
 '4D SEDAN LS',
 '4D SEDAN 1.8S',
 '4D SUV 4.0L FFV XLT',
 '4D SEDAN',
 '4D SUV 4.7L',
 '4D SEDAN I',
 '4D SEDAN',
 '4D SUV 4.7L SLT',
 '4D SUV 4.2L LS',
 '4D SUV 4.2L LS',
 '4D SEDAN LX',
 '4D SEDAN CE',
 'MINIVAN 3.8L SPORT',
 '4D SEDAN S',
 'PASSENGER EXT 3.4L LS',
 '4D SEDAN SE',
 '4D SUV 4.2L',
 'REG CAB 4.3L',
 '4D SEDAN',
 '4D SEDAN ES',
 '4D SUV 5.7L SLT',
 '4D SUV 4.7L SLT',
 '2D COUPE SE AUTO',
 'MINIVAN 3.3L',
 '4D SEDAN',
 '4D SUV LS',
 '4D SEDAN GT2',
 '4D SEDAN ZX4',
 '4D SUV 4.0L XLT',
 'REG CAB 3.7L',
 '4D SEDAN S',
 '4D WAGON',
 '4D SEDAN',
 '2D COUPE LS',
 '4D SEDAN SE',
 '4D SEDAN EX',
 '4D SEDAN',
 '4D SEDAN LS',
 '4D SPORT',
 '4D SPORT',
 '4D SEDAN 3.5L',
 '4D SEDAN LT',
 'MINIVAN 3.3L',
 '4D SEDAN ZX4',
 '4D WAGON',
 '2D COUPE LS',
 '2D COUPE SE',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN LX',
 'MINIVAN 3.3L',
 '2D HATCKBACK SI 5SP',
 '4D SEDAN',
 '4D SEDAN LIMITED',
 '4D SUV SPORT',
 '4D SUV 4.2L',
 '4D SEDAN LT 3.5L',
 'WAGON 3.5L SXT',
 '4D SEDAN',
 '4D SEDAN CX',
 '2D COUPE',
 '4D SEDAN LEVEL 2',
 'MINIVAN 3.8L',
 'WAGON 3.5L SXT',
 '4D SEDAN LT 3.5L',
 '4D SEDAN SE',
 '4D SEDAN LT 3.5L FFV',
 '4D SEDAN',
 '4D SPORT TOURING',
 'MINIVAN 3.3L',
 '2D COUPE',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN LT',
 '4D SEDAN',
 '4D SEDAN',
 'MINIVAN 3.3L',
 '4D SEDAN SEL',
 'MINIVAN 2.4L',
 '4D SEDAN CLASSIC',
 '2D QUAD COUPE LEVEL 3',
 '4D SEDAN SEL',
 '4D SEDAN EX AUTO',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN GT',
 '4D SUV 4.0L FFV XLS',
 '4D SEDAN LT',
 '4D SEDAN S',
 '4D SEDAN',
 '4D SEDAN GLE',
 '4D SEDAN GT2',
 '4D SEDAN',
 '4D SEDAN ZX4',
 '2D COUPE GS',
 '4D SEDAN LS',
 '4D SUV 4.2L LS',
 '4D SEDAN SEL',
 '4D SUV',
 '4D SEDAN LS',
 '4D SEDAN GTP',
 '4D SEDAN SE',
 '4D SEDAN SE',
 '4D SEDAN 2.7L SE',
 '4D SEDAN',
 '4D SEDAN LS',
 '4D SEDAN',
 '4D SUV LS',
 '2D COUPE',
 '4D WAGON SXT',
 'MINIVAN 3.8L',
 '2D CONVERTIBLE',
 '4D CUV 3.0L SEL',
 '4D SPORT UTILITY I',
 'WAGON 3.5L SXT',
 '4D SPORT',
 '4D SEDAN',
 '4D SEDAN LT 3.9L',
 '4D WAGON CX',
 '4D SEDAN CE',
 '4D SEDAN SE',
 '4D SUV',
 '4D SEDAN 3.5L SE',
 '4D SEDAN SE',
 '4D SEDAN EX',
 '4D SEDAN',
 'MINIVAN 3.3L SXT',
 '4D SEDAN',
 '4D SEDAN',
 '4D CUV 3.0L SE',
 '4D SEDAN',
 'PASSENGER EXT 3.5L',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SEDAN ES',
 '4D CUV 3.0L SE',
 '4D WAGON',
 '4D SEDAN CE',
 'PASSENGER 3.8L LX',
 '4D SPORT UTILITY 2.5X',
 '4D SEDAN CUSTOM',
 '4D SPORT UTILITY XE',
 '4D SUV 2.2L LS',
 '4D SPORT UTILITY 2.5X',
 'EXT CAB 4.7L SLT',
 'MINIVAN 3.8L SXT',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SEDAN LS',
 '2D COUPE GT1',
 '4D SEDAN',
 '4D SEDAN LT',
 '4D SEDAN',
 '4D SEDAN LS',
 'MINIVAN 3.3L',
 '4D SEDAN',
 '4D SEDAN LS',
 '4D SEDAN LEVEL 2',
 'PASSENGER 3.9L',
 '4D SEDAN LEVEL 2',
 '4D SEDAN',
 'PASSENGER EXT 3.5L',
 '4D SEDAN',
 '4D SEDAN EX',
 '4D SEDAN LS',
 '4D SEDAN LXI',
 '4D SEDAN EX',
 '4D SEDAN GL2',
 '2D COUPE GS',
 '4D SEDAN',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SEDAN GS',
 '4D SEDAN',
 '4D SEDAN LT 3.5L FFV',
 '4D SEDAN LS',
 '4D SEDAN CLASSIC',
 '4D SEDAN GT2',
 '2D CONVERTIBLE SE',
 '4D SEDAN LEVEL 2',
 '2D COUPE',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN EX',
 '4D SEDAN LS',
 '4D SEDAN GLS',
 '4D HATCHBACK GS',
 '4D SUV 5.3L LS',
 '4D SEDAN EX',
 '4D SEDAN GLS',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SEDAN LS',
 '4D SEDAN',
 '4D SEDAN',
 'EXT CAB 4.3L',
 '4D WAGON',
 '4D SEDAN LS',
 '4D SEDAN LS',
 '4D SEDAN ZX4',
 '4D SEDAN',
 '4D SEDAN LS 3.5L FFV',
 '4D SUV 3.7L SLT',
 '4D SEDAN',
 'MINIVAN 2.4L',
 '4D SEDAN SE',
 '4D SEDAN',
 '4D SEDAN SEL',
 '4D SEDAN LS',
 '4D SUV 4.0L FFV XLT',
 '4D SEDAN',
 '4D UTILITY 4.2L',
 '4D SEDAN',
 '4D SEDAN LX AUTO',
 '4D SUV',
 '4D SEDAN',
 '4D SEDAN EX',
 '2D COUPE',
 '4D SEDAN LEVEL 2',
 'MINIVAN 3.8L EX',
 '4D SEDAN LX',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN',
 '4D CUV 2.3L XLS',
 '4D SEDAN LEVEL 2',
 '4D SEDAN LT',
 '4D SEDAN XR',
 '4D SEDAN LT',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN 2.7L',
 '4D SEDAN LX',
 '4D SEDAN PKG1',
 '4D SUV',
 'REG CAB 2.3L EDGE',
 '4D SEDAN SEL',
 '4D SEDAN',
 '4D SEDAN SE',
 '4D SEDAN LT 3.8L FFV',
 '4D SPORT UTILITY LX',
 'EXT CAB 4.8L',
 '4D CUV 3.0L XLT',
 'REG CAB 4.2L STX',
 '4D SEDAN',
 '2D COUPE',
 '4D SEDAN SE',
 '4D SEDAN LXI',
 '2D COUPE GT',
 '4D SEDAN TOURING',
 '4D SEDAN',
 '4D WAGON',
 '4D SUV',
 '4D SEDAN LT',
 '4D SEDAN',
 '4D SEDAN',
 '4D SEDAN LEVEL 2',
 '4D SEDAN SE1',
 '4D SEDAN SES',
 '4D SEDAN',
 '4D SPORT',
 '4D SEDAN SE1',
 '4D SPORT UTILITY LX',
 '4D SEDAN EX',
 '4D SEDAN',
 '4D SEDAN',
 'MINIVAN 3.3L SE',
 '4D SEDAN LX',
 '4D PASSENGER 3.9L SES',
 '2D COUPE SVT',
 '4D SUV LS',
 '4D SUV 4.2L LS',
 'MINIVAN 3.3L FFV SE',
 '4D SEDAN SE',
 '2D CONVERTIBLE',
 '4D CUV 3.0L LIMITED',
 'MINIVAN 3.3L',
 'QUAD CAB 4.7L SPORT',
 '4D SUV 4.2L LS',
 '4D SEDAN',
 '4D SEDAN LS',
 '4D SEDAN LS',
 '4D SEDAN LIMITED',
 '2D COUPE GLS',
 '4D SUV 4.2L LS',
 '2D COUPE ZX3',
 '2D COUPE GT',
 '4D SUV 4.2L',
 '4D PASSENGER 3.9L SES',
 '4D SEDAN',
 '4D SPORT UTILITY',
 '4D SEDAN LS',
 '2D COUPE',
 'PASSENGER EXT 3.4L',
 '4D SEDAN ZX4 SE',
 '4D WAGON LAREDO',
 '4D SEDAN LS',
 '4D SEDAN ES',
 '4D SEDAN SE1',
 '4D WAGON LW300',
 '4D SEDAN',
 '4D SEDAN TOURING',
 '4D SEDAN',
 '4D SEDAN CUSTOM',
 '4D SPORT UTILITY',
 '4D PASSENGER 3.8L SE',
 '4D SUV 4.7L SLT',
 '4D SEDAN 1.8',
 ...]

In [62]:
#Focus on submodel series with a small sample and split at the '.'
en_sizes = chars.SubModel[0:10000].str.split('.').reset_index()
en_sizes.head()

   index              SubModel
0      0          [4D SEDAN I]
1      1  [QUAD CAB 4, 7L SLT]
2      2    [4D SEDAN SXT FFV]
3      3            [4D SEDAN]
4      4        [2D COUPE ZX3]

In [65]:
#Only keep entries with engine size len(Submodel) == 2
en_sizes2 = []
for model in en_sizes.SubModel:
       if len(model) == 2:
            en_sizes2.append(model)

            en_sizes2[:5]

[['QUAD CAB 4', '7L SLT'],
 ['REG CAB 4', '3L'],
 ['REG CAB 4', '2L XL'],
 ['MINIVAN 3', '3L'],
 ['MINIVAN 3', '8L']]

In [67]:
#Finally take the last element from 1st list, insert '.' add lasr element of 2nd list
en_sizes3 = []
for i in range(len(en_sizes2)):
    beg = en_sizes2[i][0][-1]
    end = en_sizes2[i][1][0]
    whole = beg+'.'+end
    en_sizes3.append(whole)

In [73]:
#check most common en sizes
e_displace = pd.Series(en_sizes3)
e_displace.value_counts().head()

3.5    479
4.2    390
3.3    336
4.7    261
3.0    167
dtype: int64

In [77]:
disp = chars.SubModel[0:5000]

In [84]:
keydisp = [e_displace.unique()[:3]]
keydisp

[array(['4.7', '4.3', '4.2'], dtype=object)]

In [85]:
keydisp = e_displace.unique()[:3]
dis_val_sets = pd.DataFrame()
for key in keydisp:
    for i in disp:
        vals = np.where(disp.str.contains('' + str(key) + ''),1,0)
    dis_val_sets[key] = vals

In [86]:
dis_val_sets

      4.7  4.3  4.2
0       0    0    0
1       1    0    0
2       0    0    0
3       0    0    0
4       0    0    0
5       0    0    0
6       0    0    0
7       0    0    0
8       0    0    0
9       0    0    0
10      0    1    0
11      0    0    1
12      0    0    0
13      0    0    0
14      0    0    0
15      0    0    0
16      0    0    1
17      0    0    0
18      0    0    1
19      0    0    0
20      0    0    0
21      0    0    0
22      0    0    0
23      0    0    0
24      0    0    0
25      0    0    1
26      1    0    0
27      0    0    0
28      0    0    0
29      0    0    0
...   ...  ...  ...
4970    0    0    0
4971    0    0    0
4972    0    0    0
4973    0    0    0
4974    0    0    0
4975    0    0    0
4976    0    0    0
4977    0    0    0
4978    0    0    0
4979    0    0    0
4980    0    0    0
4981    0    0    0
4982    0    0    0
4983    0    0    0
4984    0    0    0
4985    0    0    0
4986    0    0    0
4987    0    0    0
4988    0    0    0
4989    0    0    0
4990    0    0    0
4991    0    0    0
4992    0    0    0
4993    0    0    1
4994    0    0    0
4995    0    0    0
4996    0    0    0
4997    0    0    0
4998    0    0    0
4999    0    0    0

[5000 rows x 3 columns]